exports.INVALID_SUBSCRIPTION = 'INVALID_SUBSCRIPTION';
exports.UNAUTHORIZED = 'UNAUTHORIZED';
exports.INVALID_REQUEST = 'INVALID_REQUEST';
exports.INVALID_USER = 'INVALID_USER';
exports.INVALID_PASSWORD = 'INVALID_PASSWORD';
exports.INVALID_EMAIL = 'INVALID_EMAIL';
exports.INVALID_TOKEN = 'INVALID_TOKEN';